version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install -g typescript
      - npm install -g @nestjs/cli
      - npm install
  build:
    commands:
      - echo Build started on `date`...
      - echo Compiling the source code...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`...
artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - tsconfig.json
    - 'dist/**/*'
